services:
  identity-postgres:
    image: postgres:16.3-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=identity
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: